# Generated by Django 3.0.8 on 2020-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200722_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Fristname')),
                ('lastname', models.CharField(max_length=255, verbose_name='Lastname')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=900, verbose_name='Description')),
                ('list_title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='List title1 ')),
                ('list_list1', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list2')),
                ('list_list2', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list3')),
                ('list_list3', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list4')),
                ('list_list4', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list5')),
                ('list_list5', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list6')),
                ('list_title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='List title2 ')),
                ('list_list6', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list1')),
                ('list_list7', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list2')),
                ('list_list8', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list3')),
                ('list_list9', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list4')),
                ('list_list10', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list5')),
                ('list_title3', models.CharField(blank=True, max_length=255, null=True, verbose_name='List title3 ')),
                ('list_list11', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list1')),
                ('list_list12', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list2')),
                ('list_list13', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list3')),
                ('list_list14', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list4')),
                ('list_list15', models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list5')),
            ],
            options={
                'verbose_name': 'Human resource',
                'verbose_name_plural': 'Human resources',
            },
        ),
    ]
