# Generated by Django 3.0.8 on 2020-07-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200730_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='list_title',
        ),
        migrations.RemoveField(
            model_name='listtitle',
            name='list_item',
        ),
        migrations.AddField(
            model_name='listitem',
            name='list_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ListTitle', verbose_name='List title'),
        ),
        migrations.AddField(
            model_name='listtitle',
            name='open_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Hr', verbose_name='Open job'),
        ),
    ]
