# Generated by Django 3.0.8 on 2020-08-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200730_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Request Lesson',
                'verbose_name_plural': 'Request Lesson',
                'ordering': ['name'],
            },
        ),
    ]
