# Generated by Django 3.0.8 on 2020-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=900, verbose_name='Description')),
                ('list_title', models.CharField(max_length=255, verbose_name='List title ')),
                ('list_list', models.CharField(max_length=900, verbose_name='Lists list')),
            ],
            options={
                'verbose_name': 'Human resource',
                'verbose_name_plural': 'Human resources',
            },
        ),
    ]
