# Generated by Django 3.0.8 on 2020-07-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Fristname')),
                ('lastname', models.CharField(max_length=255, verbose_name='Lastname')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('attach_pdf', models.FileField(upload_to='media/application/')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
