# Generated by Django 3.0.8 on 2020-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='list_title',
            new_name='list_title1',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='list_list',
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list1',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list10',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list11',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list12',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list13',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list14',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list15',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list2',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list3',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list4',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list5',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list6',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list7',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list8',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_list9',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Lists list'),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='List title '),
        ),
        migrations.AddField(
            model_name='hr',
            name='list_title3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='List title '),
        ),
    ]
